// <auto-generated />
using System;
using DesafioConnectSea.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioConnectSea.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DesafioConnectSeaDbContext))]
    [Migration("20260103234406_AddSeedTables")]
    partial class AddSeedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioConnectSea.Domain.Entities.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Eta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Porto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Escalas");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Eta = new DateTime(2025, 8, 27, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Navio = "MV Atlas",
                            Porto = "BRRGD - RIO GRANDE",
                            Status = 1
                        },
                        new
                        {
                            Id = 202,
                            Eta = new DateTime(2025, 8, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Navio = "MV Atlas",
                            Porto = "BRITJ - ITAJAI",
                            Status = 2
                        },
                        new
                        {
                            Id = 203,
                            Eta = new DateTime(2025, 8, 29, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Navio = "MV Atlas",
                            Porto = "BRPNG - PARANAGUA",
                            Status = 1
                        },
                        new
                        {
                            Id = 204,
                            Eta = new DateTime(2025, 8, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Navio = "MV Atlas",
                            Porto = "BRSSZ - SANTOS",
                            Status = 1
                        },
                        new
                        {
                            Id = 301,
                            Eta = new DateTime(2025, 8, 22, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Navio = "MV Poseidon",
                            Porto = "BRRGD - RIO GRANDE",
                            Status = 4
                        },
                        new
                        {
                            Id = 302,
                            Eta = new DateTime(2025, 8, 24, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Navio = "MV Poseidon",
                            Porto = "BRITJ - ITAJAI",
                            Status = 3
                        },
                        new
                        {
                            Id = 303,
                            Eta = new DateTime(2025, 8, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Navio = "MV Poseidon",
                            Porto = "BRSSZ - SANTOS",
                            Status = 1
                        });
                });

            modelBuilder.Entity("DesafioConnectSea.Domain.Entities.Manifesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortoDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortoOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Manifestos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Navio = "MV Atlas",
                            Numero = "IMP-2025-0001",
                            PortoDestino = "BR SANTOS",
                            PortoOrigem = "CN SHANGHAI",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Navio = "MV Poseidon",
                            Numero = "EXP-2025-0042",
                            PortoDestino = "NL ROTTERDAM",
                            PortoOrigem = "BR RIO GRANDE",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Navio = "MV Hermes",
                            Numero = "IMP-2025-0099",
                            PortoDestino = "BR SANTOS",
                            PortoOrigem = "US MIAMI",
                            Tipo = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
